"""fifth Migration

Revision ID: 027e816edff2
Revises: 35caf21ea940
Create Date: 2024-10-06 17:16:30.682719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027e816edff2'
down_revision = '35caf21ea940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('age_transition_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('to_unit', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('age_transition_notifications', schema=None) as batch_op:
        batch_op.drop_column('to_unit')
        batch_op.drop_column('from_unit')

    # ### end Alembic commands ###
