"""Added image column on events

Revision ID: 2fc00e9c4956
Revises: ff03d707338d
Create Date: 2024-10-30 02:46:07.521571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc00e9c4956'
down_revision = 'ff03d707338d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('organizer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('organizer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('image')

    # ### end Alembic commands ###
