"""ninth Migration

Revision ID: 34531e82c528
Revises: d72ee1e2f779
Create Date: 2024-10-06 18:02:58.017317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34531e82c528'
down_revision = 'd72ee1e2f779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('age_transition_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('to_unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notification_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('age_transition_status', sa.String(length=20), nullable=True))
        batch_op.drop_column('new_age')
        batch_op.drop_column('old_age')
        batch_op.drop_column('transition_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('age_transition_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transition_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('old_age', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('new_age', sa.INTEGER(), nullable=True))
        batch_op.drop_column('age_transition_status')
        batch_op.drop_column('notification_date')
        batch_op.drop_column('to_unit')
        batch_op.drop_column('from_unit')

    # ### end Alembic commands ###
