"""fourth Migration

Revision ID: 35caf21ea940
Revises: d22d3bd1f4b0
Create Date: 2024-10-06 17:13:59.858310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35caf21ea940'
down_revision = 'd22d3bd1f4b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('age_transition_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_transition_status', sa.String(length=20), nullable=True))
        batch_op.drop_column('to_unit')
        batch_op.drop_column('status')
        batch_op.drop_column('from_unit')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('subscription_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_date')
        batch_op.drop_column('subscription_amount')

    with op.batch_alter_table('age_transition_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_unit', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('to_unit', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('age_transition_status')

    # ### end Alembic commands ###
