"""updated to have default registration payment amount

Revision ID: 47626039e23c
Revises: f11eff6a696c
Create Date: 2024-12-17 16:40:33.197087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47626039e23c'
down_revision = 'f11eff6a696c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_fee_default', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youths', schema=None) as batch_op:
        batch_op.drop_column('registration_fee_default')

    # ### end Alembic commands ###
