"""sixth Migration

Revision ID: 505e798dd4e4
Revises: 027e816edff2
Create Date: 2024-10-06 17:17:50.330962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505e798dd4e4'
down_revision = '027e816edff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('age_transition_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('age_transition_notifications', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
