"""updated events

Revision ID: 51a7978de095
Revises: 9b4b8b8734ae
Create Date: 2024-11-10 12:52:59.994084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a7978de095'
down_revision = '9b4b8b8734ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_events_school_id_schools'), 'schools', ['school_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_events_school_id_schools'), type_='foreignkey')
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###
