"""updated attendance to events

Revision ID: 5b669be48c90
Revises: caa89a3bba00
Create Date: 2024-11-16 14:58:53.725821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b669be48c90'
down_revision = 'caa89a3bba00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('youth_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('attendance_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_attendances_event_id_events')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_attendances_school_id_schools')),
    sa.ForeignKeyConstraint(['youth_id'], ['youths.id'], name=op.f('fk_attendances_youth_id_youths')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendances')
    # ### end Alembic commands ###
