"""ninth Migration

Revision ID: 73679fa4b81d
Revises: 34531e82c528
Create Date: 2024-10-06 18:18:22.090483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73679fa4b81d'
down_revision = '34531e82c528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_payments_student_id_students', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_payments_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_payments_school_id_schools'), 'schools', ['school_id'], ['id'])
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_payments_school_id_schools'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_payments_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_payments_student_id_students', 'students', ['student_id'], ['id'])
        batch_op.drop_column('school_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
