"""Second Migration

Revision ID: 7cc759d72763
Revises: 31f5360aa27b
Create Date: 2024-10-11 16:12:33.691076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc759d72763'
down_revision = '31f5360aa27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parentName', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('parentPhone', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('parentPhone')
        batch_op.drop_column('parentName')

    # ### end Alembic commands ###
