"""added automatic payment yearly payment update

Revision ID: 9b4b8b8734ae
Revises: b447d9ce4ec3
Create Date: 2024-11-07 14:34:19.372052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b4b8b8734ae'
down_revision = 'b447d9ce4ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_reports')
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('youths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yearly_total_payment', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youths', schema=None) as batch_op:
        batch_op.drop_column('last_updated_at')
        batch_op.drop_column('yearly_total_payment')

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('last_updated_at')

    op.create_table('financial_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('total_income', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_expenditure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('net_profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='fk_financial_reports_school_id_schools'),
    sa.PrimaryKeyConstraint('id', name='financial_reports_pkey')
    )
    # ### end Alembic commands ###
