"""update to incorprate yearly total amount

Revision ID: b447d9ce4ec3
Revises: 2fc00e9c4956
Create Date: 2024-11-07 12:14:57.840150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b447d9ce4ec3'
down_revision = '2fc00e9c4956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yearly_total_payment', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('yearly_total_payment')

    # ### end Alembic commands ###
