"""Updated youths to have commitee and commisioner membmbers

Revision ID: c730a1d79e82
Revises: 1b3022633498
Create Date: 2024-12-09 21:25:46.569707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c730a1d79e82'
down_revision = '1b3022633498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commissioner', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('commitee', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youths', schema=None) as batch_op:
        batch_op.drop_column('commitee')
        batch_op.drop_column('commissioner')

    # ### end Alembic commands ###
