"""Added roles to youths

Revision ID: d24c4c260ae9
Revises: f4bb525691a7
Create Date: 2024-10-21 10:46:44.186813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24c4c260ae9'
down_revision = 'f4bb525691a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youths', schema=None) as batch_op:
        batch_op.drop_column('roles')

    # ### end Alembic commands ###
