"""eight Migration

Revision ID: d72ee1e2f779
Revises: 505e798dd4e4
Create Date: 2024-10-06 18:01:20.618346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72ee1e2f779'
down_revision = '505e798dd4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('age_transition_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transition_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('old_age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('new_age', sa.Integer(), nullable=True))
        batch_op.drop_column('to_unit')
        batch_op.drop_column('age_transition_status')
        batch_op.drop_column('from_unit')
        batch_op.drop_column('notification_date')

    with op.batch_alter_table('payment_reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_reminders', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('age_transition_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('from_unit', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('age_transition_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('to_unit', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('new_age')
        batch_op.drop_column('old_age')
        batch_op.drop_column('transition_date')

    # ### end Alembic commands ###
