"""Added merchantId to payments as Identifier

Revision ID: ff03d707338d
Revises: 628287352454
Create Date: 2024-10-30 01:57:08.624242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff03d707338d'
down_revision = '628287352454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['merchant_request_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('merchant_request_id')

    # ### end Alembic commands ###
